server:
  port: 8082

spring:
  application:
    name: Student
  datasource:
    url: jdbc:mysql://localhost:3306/userservice
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
